In [3]:
##怎么样用python进行数据分析 

# 2.Numpy建立一维数据结构

In [16]:
  # 一维数据建立
import numpy as np


In [17]:
import pandas as pd

In [22]:
#定义一维数组
a = np.array([2,3,4,5])


In [23]:
#查询元素
a[0]

2

In [30]:
#切片访问
a[:2]

array([2, 3])

In [ ]:
#循环访问
for i 

In [31]:
#数据类型
a.dtype

dtype('int32')

In [34]:
#平均值
a.mean()

3.5

In [37]:
#方差
a.std()


1.118033988749895

In [39]:
#引进新的数组b
b=np.array([4,3,2,1])

In [41]:
c=a+b

In [44]:
c

array([6, 6, 6, 6])

In [46]:
print(c)

[6 6 6 6]


In [54]:
#数组的乘法
d=3*c

In [56]:
d

array([18, 18, 18, 18])

In [57]:
print(d)    

[18 18 18 18]


In [59]:
print(d[3])

18


# 3.pandas 一维数据结构


In [63]:
import pandas as pd

In [64]:
#定义：Pandas一维数据结构:Series
#存放6家公司某一天的股价（单位是美元）。其中腾讯427.4港元兑换成美元是54.74
stockS=pd.Series([54.74,190.9,173.14,1050.3,181.86,1139.49],
                index=['腾讯',
                       '阿里巴巴',
                       '苹果',
                       '谷歌',
                       'Facebook',
                       '亚马逊'])

In [67]:
#获取描述信息
stockS.describe()

count       6.000000
mean      465.071667
std       491.183757
min        54.740000
25%       175.320000
50%       186.380000
75%       835.450000
max      1139.490000
dtype: float64

In [71]:
#iloc根据位置获取值
stockS.iloc[1]

190.9

In [73]:
#loc 根据索引获取值
stockS.loc['阿里巴巴']

190.9

In [79]:
#向量化运算：向量相加
O=pd.Series([1,2,3,4],index=['a','b','c','d'])
P=pd.Series([2,3,4,5],index=['a','b','e','f'])
Q=O+P

In [80]:
Q

a    3.0
b    5.0
c    NaN
d    NaN
e    NaN
f    NaN
dtype: float64

In [82]:
#方法一 删除缺失值
Q.dropna()

a    3.0
b    5.0
dtype: float64

In [84]:
#方法二 将缺失值填充为0
Q=O.add(P,fill_value=0)

In [85]:
Q

a    3.0
b    5.0
c    3.0
d    4.0
e    4.0
f    5.0
dtype: float64