###  4.NumPy二维数据结构

In [1]:
import numpy as np

In [2]:
#定义二维数组Numpy
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# 查询方式：3种方法
 #（1）直接精确到某值
 #（2）精确到某行
 #（3）精确到某列


In [6]:
 #（1）直接精确到某值
    #从0行0列开始
a[0,3]

4

In [7]:
#(2)精确到某行
a[1,1:3]

array([6, 7])

In [8]:
#(3)精确到某列
a[:,0]

array([1, 5, 9])

In [9]:
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

数轴参数axis

In [10]:
#没有指定某行某列，全局的平均值
a.mean()

6.5

In [11]:
#指定按行计算平均值
a.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [12]:
#指定按列计算平均值
a.mean(axis=0)

array([5., 6., 7., 8.])

In [13]:
a.std()

3.452052529534663

In [14]:
a.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

### 5.二维数据分析pandas 
   数据框 Data Framne

In [15]:
import pandas as pd

In [16]:
'''
Pandas二维数组：数据框（DataFrame） 
'''
#第1步：定义一个字典，映射列名与对应列的值
salesDict={
    '购药时间':['2018-01-01 星期五','2018-01-02 星期六','2018-01-06 星期三'],
    '社保卡号':['001616528','001616528','0012602828'],
    '商品编码':[236701,236701,236701],
    '商品名称':['强力VC银翘片','清热解毒口服液','感康'],
    '销售数量':[6,1,2],
    '应收金额':[82.8,28,16.8],
    '实收金额':[69,24.64,15]
}
# 导入有序字典(注意定义时候字母开头需要大写)
from collections import OrderedDict
#定义一个有序字典
salesOrderDict=OrderedDict(salesDict)
#定义数据框：传入字典，列名
salesDf=pd.DataFrame(salesOrderDict)

In [17]:
salesDf

购药时间        社保卡号    商品编码     商品名称  销售数量  应收金额   实收金额
0  2018-01-01 星期五   001616528  236701  强力VC银翘片     6  82.8  69.00
1  2018-01-02 星期六   001616528  236701  清热解毒口服液     1  28.0  24.64
2  2018-01-06 星期三  0012602828  236701       感康     2  16.8  15.00

In [18]:
#不进行排序，做个对比，状态较差
salesDict

{'购药时间': ['2018-01-01 星期五', '2018-01-02 星期六', '2018-01-06 星期三'],
 '社保卡号': ['001616528', '001616528', '0012602828'],
 '商品编码': [236701, 236701, 236701],
 '商品名称': ['强力VC银翘片', '清热解毒口服液', '感康'],
 '销售数量': [6, 1, 2],
 '应收金额': [82.8, 28, 16.8],
 '实收金额': [69, 24.64, 15]}

In [19]:
salesDf.mean()

社保卡号    5.388427e+24
商品编码    2.367010e+05
销售数量    3.000000e+00
应收金额    4.253333e+01
实收金额    3.621333e+01
dtype: float64

In [20]:
#iloc用于根据位置进行查询值
 #查询元素
salesDf.iloc[0,1]

'001616528'

In [91]:
#查找某行元素,会把标签行也会带上
salesDf.iloc[0:2,0:3]

购药时间       社保卡号      商品编码
0  2018-01-01 星期五  1616528.0  236701.0
1  2018-01-02 星期六  1616528.0  236701.0

In [22]:
#查找某列元素，也会把标签信息带出来
salesDf.iloc[:,0]

0    2018-01-01 星期五
1    2018-01-02 星期六
2    2018-01-06 星期三
Name: 购药时间, dtype: object

In [92]:
#loc用于根据位置来求索引值，列的索引值除了：号，其余查找时，需要打单引号括起来。
 #查询元素
salesDf.loc[0:3,'商品编码']

0    236701.0
1    236701.0
2    236701.0
3    236701.0
Name: 商品编码, dtype: float64

In [89]:
 #查询某行
salesDf.loc[0:2,:]

购药时间        社保卡号      商品编码     商品名称  销售数量  应收金额   实收金额
0  2018-01-01 星期五   1616528.0  236701.0  强力VC银翘片   6.0  82.8  69.00
1  2018-01-02 星期六   1616528.0  236701.0  清热解毒口服液   1.0  28.0  24.64
2  2018-01-06 星期三  12602828.0  236701.0       感康   2.0  16.8  15.00

In [30]:
#查询某列
salesDf.loc[:,'商品名称']

0    强力VC银翘片
1    清热解毒口服液
2         感康
Name: 商品名称, dtype: object

In [32]:
#查询某几列
salesDf.loc[:,'商品名称']

0    强力VC银翘片
1    清热解毒口服液
2         感康
Name: 商品名称, dtype: object

In [37]:
salesDf['商品名称']

0    强力VC银翘片
1    清热解毒口服液
2         感康
Name: 商品名称, dtype: object

In [38]:
#当查询两列以上时，通过【】将所要求的几列都排序出来，不要忘记[]
salesDf[['商品名称','销售数量']]

商品名称  销售数量
0  强力VC银翘片     6
1  清热解毒口服液     1
2       感康     2

In [85]:
#切片功能:指定范围 记得加：（双引号）来隔开
salesDf.loc[1:2,'商品名称':'销售数量']

商品名称  销售数量
1  清热解毒口服液   1.0
2       感康   2.0

#### pandas条件判断筛选查询

In [59]:
#1.查询条件判断查询
querySer=salesDf.loc[:,'销售数量']>1.1

In [58]:
type(querySer)

pandas.core.series.Series

In [60]:
querySer

0     True
1    False
2     True
Name: 销售数量, dtype: bool

In [61]:
#2.利用查询条件
salesDf.loc[querySer,:]

购药时间        社保卡号    商品编码     商品名称  销售数量  应收金额  实收金额
0  2018-01-01 星期五   001616528  236701  强力VC银翘片     6  82.8  69.0
2  2018-01-06 星期三  0012602828  236701       感康     2  16.8  15.0

#### 描述统计分析

In [67]:
#读取Ecxcel数据
'''
路径中最好不要有中文，或者特殊符号啥的，不然路径会提示错误找不到。
最好将文件放到一个简单的英文路径下，比如D盘
在本地运行时替换成你自己的实际数据的文件路径
'''
#文件路径
fileNameStr='E:\\test\\医院销售数据.xlsx'
'''
使用pandas的read_excel函数读取Ecxcel数据
参数sheet_name：数据在Excel里的哪个sheet下面，这块就写该sheet在excel里的名称
pandas的read_excel函数官网地址：https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html#pandas.read_excel
'''
salesDf = pd.read_excel(fileNameStr,sheet_name='Sheet1')

In [69]:
type(fileNameStr)

str

In [71]:
salesDf

购药时间          社保卡号       商品编码     商品名称  销售数量   应收金额    实收金额
0     2018-01-01 星期五  1.616528e+06   236701.0  强力VC银翘片   6.0   82.8   69.00
1     2018-01-02 星期六  1.616528e+06   236701.0  清热解毒口服液   1.0   28.0   24.64
2     2018-01-06 星期三  1.260283e+07   236701.0       感康   2.0   16.8   15.00
3     2018-01-11 星期一  1.007034e+10   236701.0    三九感冒灵   1.0   28.0   28.00
4     2018-01-15 星期五  1.015543e+08   236701.0    三九感冒灵   8.0  224.0  208.00
...              ...           ...        ...      ...   ...    ...     ...
6573  2018-04-27 星期三  1.078861e+08  2367011.0      高特灵  10.0   56.0   54.80
6574             NaN           NaN        NaN      NaN   NaN    NaN     NaN
6575  2018-04-27 星期三  1.008787e+10  2367011.0      高特灵   2.0   11.2    9.86
6576  2018-04-27 星期三  1.340663e+07  2367011.0      高特灵   1.0    5.6    5.00
6577  2018-04-28 星期四  1.192693e+07  2367011.0      高特灵   2.0   11.2   10.00

[6578 rows x 7 columns]

In [74]:
#通过head()来查询前几行，如果不写，默认查前5行
salesDf.head(2)

购药时间       社保卡号      商品编码     商品名称  销售数量  应收金额   实收金额
0  2018-01-01 星期五  1616528.0  236701.0  强力VC银翘片   6.0  82.8  69.00
1  2018-01-02 星期六  1616528.0  236701.0  清热解毒口服液   1.0  28.0  24.64

In [76]:
#查看某一列的数据类型，需要通过loc来定位
salesDf.loc[:,'商品编码'].dtype

dtype('float64')

In [83]:
#查看列的类型，只能查某一列
salesDf.loc[:,'销售数量'].dtype

dtype('float64')

In [78]:
#查找多少行，多少列
salesDf.shape

(6578, 7)

In [79]:
#每一列的描述信息
salesDf.describe()

社保卡号          商品编码         销售数量         应收金额         实收金额
count  6.576000e+03  6.577000e+03  6577.000000  6577.000000  6577.000000
mean   6.091254e+09  1.015869e+06     2.386194    50.473803    46.317510
std    4.889284e+09  5.131153e+05     2.375202    87.595925    80.976702
min    1.616528e+06  2.367010e+05   -10.000000  -374.000000  -374.000000
25%    1.014234e+08  8.614560e+05     1.000000    14.000000    12.320000
50%    1.001650e+10  8.615070e+05     2.000000    28.000000    26.600000
75%    1.004882e+10  8.690690e+05     2.000000    59.600000    53.000000
max    1.283612e+10  2.367012e+06    50.000000  2950.000000  2650.000000